<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Application_of_Linear_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Systems of Linear Equations
##Systems of Linear Equations can be solved with arrays and NumPy

In [2]:
import numpy as np

A = np.array([[4,5],[3,-2]])
print(A)

B = np.array([[7],[11]])
print(B)

##1st possible solution
inv_A = np.linalg.inv(A)
print(inv_A)
X = np.dot(inv_A,B)
print(X)

##shorter version of 1st sol'n
x = np.linalg.inv(A).dot(B)
print(x)

[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]
[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]
[[ 3.]
 [-1.]]


In [3]:
##NP.LINALG.SOLVE
import numpy as np
X = np.linalg.solve(A,B)
print(X)



[[ 3.]
 [-1.]]


In [7]:
##use of SciPy
from scipy.linalg import solve
X = solve(A,B)
print(X)

[[ 3.]
 [-1.]]
