<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Transpose 3x3

In [67]:
import numpy as np
A = np.array([[1,2,3], [4,5,6], [7,8,9]]) #instiantiate an array first
print("Original Matrix \n", A,"\n")

B = np.transpose(A) #then transpose using numpy command
print("Transposed Matrix")
print(B)


Original Matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Transposed Matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#Transpose 4x4

In [68]:
import numpy as np
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) #instiantiate an array first
print("Original Matrix \n", A,"\n")

B = np.transpose(A) #then transpose using numpy command
print("Transposed Matrix")
print(B)


Original Matrix 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Transposed Matrix
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


#Inverse 3x3

In [116]:
import numpy as np
A=np.array([[11,12,13],[14,15,16],[17,18,19]]) #instiantiate an array first
print("Original Matrix \n", A,"\n")

B=np.linalg.inv(A)
print("Inversed Matrix")
print(B)

Original Matrix 
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

Inversed Matrix
[[ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]]


#Inverse 4x4

In [118]:
import numpy as np
A=np.array([[1,2,2,3],[3,6,8,8],[9,9,11,12],[13,15,15,16]]) #instiantiate an array first
print("Original Matrix \n", A,"\n")

B=np.linalg.inv(A)
print("Inverse matrix")
print(B)

Original Matrix 
 [[ 1  2  2  3]
 [ 3  6  8  8]
 [ 9  9 11 12]
 [13 15 15 16]] 

Inverse matrix
[[-0.22641509 -0.24528302  0.24528302 -0.01886792]
 [ 0.18867925  0.03773585 -0.53773585  0.3490566 ]
 [-1.01886792  0.39622642  0.10377358 -0.08490566]
 [ 0.96226415 -0.20754717  0.20754717 -0.16981132]]
