<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Eigenvalue and EigenVector

In [3]:
import numpy as np
from scipy.linalg import solve

A = np.array([[-12,3],[4,1]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B = np.array([[0],[0]])
print(B)

X = np.dot(inv_A,B)
print(X)
Y = solve(A,B)
print(Y)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0]
 [0]]
[[0.]
 [0.]]
[[-0.]
 [ 0.]]


In [8]:
##Eigen Method
#Example 1

import numpy as np
from numpy.linalg import eig
A = np.array([[-6,3],[4,5]])
print(A)

##w is for eigenvalue and v is for eigenvector
w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are",v)
x=v.round()
print(x)

[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are: [-7.  6.]
The right eigenvectors are [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
[[-1. -0.]
 [ 0. -1.]]


In [15]:
#Example 2
A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are ",w)
print("The eigenvectors are ",v)

print(w.round())
print(v.round())

C = np.dot(A,v.round())
print(C)




[[2 2 4]
 [1 3 5]
 [2 3 4]]
The eigenvalue/s is/are  [ 8.80916362  0.92620912 -0.73537273]
The eigenvectors are  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
