<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [54]:
#I don't know how to solve this using code.

Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [52]:
import numpy as np
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
B = np.array([5,15,-20])
Ainv=np.linalg.inv(A)

print("Array A\n", A)
print("Array B\n", B)
print("\nThe final answer is\n", Ainv)

##shortcut method
print(np.linalg.solve(A,B))

#Explanation why the problem cannot be solved
#As you can see in the error log. The matrix is a Singular type of matrix meaning that the determinant is zero/0. Therefore the operation cannot continue any further.

LinAlgError: ignored

Find the Eigenvalue and Eigenvectors

[  8   5  -6]

 [-12  -9  12]

 [ -3  -3   5]





In [46]:
import numpy as np
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)


x,y = np.linalg.eig(A)
print("\nThe eigenvalue/s is/are:",x)

print("\nThe eigenvectors are:\n",y)


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The eigenvalue/s is/are: [-1.  3.  2.]

The eigenvectors are:
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
