<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam


Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [11]:
import numpy as np
a =np.full((5,5),0)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [12]:
import numpy as np
b = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(b)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [13]:
import numpy as np
c = np.array([[1,2,3],[2,5,2],[3,2,1]])
print(c)

[[1 2 3]
 [2 5 2]
 [3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [17]:
import numpy as np
C=np.array([[1,2,3],[2,3,3],[3,4,-2]])
print("Given Matrix C\n",C)
Cinv=np.linalg.inv(C)
print("\nInverse Matrix of C\n",Cinv)

Given Matrix C
 [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Inverse Matrix of C
 [[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [19]:
import numpy as np
C=np.array([[1,2,3],[2,3,3],[3,4,-2]])
print("Given Matrix C\n",C)
Cdet = np.linalg.det(C)
print("\nDeterminant of Matrix C\n",Cdet)

Given Matrix C
 [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Determinant of Matrix C
 5.000000000000001


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [28]:
import numpy as np 
D = np.array([[5,4,1],[10,9,4],[10,13,15]])
Dinv=np.linalg.inv(D)
E = np.array([[3.4],[8.8],[19.2]])

print(D)
print("\nInverse\n",Dinv)
print("\n",E)

##solve
ans = np.dot(Dinv,E)
print("\nFinal Answer is\n",ans)




[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

Inverse
 [[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]

 [[ 3.4]
 [ 8.8]
 [19.2]]

Final Answer is
 [[0.2]
 [0.4]
 [0.8]]
