<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1



Problem 1

In [45]:
import numpy as np

W = np.array([[1,-3],
             [2,-2],
             [3,1]])

X = np.array([[3,2,1],
            [-1,2,3],
            [2,-1,1]])

Y= np.array([[1,2,0],
           [0,-1,2]])

Z = np.array([[0,1],
            [2,3]])

#a.WY
print("a.WY")
a = np.dot(W,Y)
print(a,"\n")

#b.Z+Z
print ("b.Z+Z")
b = np.add(Z,Z)
print(b,"\n")

#c.3X
print("c.3X")
c = np.power(X, 3)
print(c,"\n")

a.WY
[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]] 

b.Z+Z
[[0 2]
 [4 6]] 

c.3X
[[27  8  1]
 [-1  8 27]
 [ 8 -1  1]] 



Problem 2

In [78]:
import numpy as np

W = np.array([[1,-3],
             [2,-2],
             [3,1]])

X = np.array([[3,2,1],
            [-1,2,3],
            [2,-1,1]])

Y= np.array([[1,2,0],
           [0,-1,2]])

Z = np.array([[0,1],
            [2,3]])

#A.The product (YW)^2 is not defined
print("A.The product (YW)2 is not defined")
A1 = np.dot(Y,W)
print(np.power(A1,2),'\n')
print(np.dot(Y,W)^2)


#B.WY-X
print("B.WY-X")
B1 = np.dot(W,Y)
B = np.subtract(B1,X)
print (B,"\n")

#C.YW – Z^2 =
print("C. YW – Z^2")
C1 = np.dot(Y,W)
C2 = np.power(Z,2)
C = np.subtract(C1,C2)
print(C)






A.The product (YW)2 is not defined
[[25 49]
 [16 16]] 

[[ 7 -5]
 [ 6  6]]
B.WY-X
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]] 

C. YW – Z^2
[[ 5 -8]
 [ 0 -5]]
