#Prelim Exam


Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [12]:
import numpy as np
C = np.diag(np.ones(4))
print(" Matrix C\n", C)


 Matrix C
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


My solution here is pretty simple.
I just instatiated an array with the needed requirements to satisfy the question using numpy commands.

In [ ]:
...
...
...
...

Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [29]:
#original code
import numpy as np
C = np.diag(np.ones(4))
print(" Matrix C\n", C)

#solution for Question 2
C1= np.repeat(C,2, axis =1)
print("\n Doubled Matrix A \n",C1)

#alternative doubled values

C2= np.repeat(C,2, axis =0)
print("\n Doubled Matrix B \n",C2)

#If "double the values" are meant by the value of the digit

C3= np.add(C,C)
print("\n Doubled Matrix C \n",C3)

 Matrix C
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Doubled Matrix A 
 [[1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]]

 Doubled Matrix B 
 [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]

 Doubled Matrix C 
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


I don't really understood the question so I put 3 answers with the same sense or understanding of "Double the Values"

In this one, I also used a numpy command, np.repeat and putting "matrix C" as the value to make it double and putting the values into the same axis in the "Doubled Matrix A" while on "Doubled Matrix B", I put them on the next line.

While on the third Matrix, I just add the same matrix on itself by using numpy functions and then print it.

In [ ]:
...
...
...
...

Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and

B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [36]:
import numpy as np
A = [2,7,4]
B = [3,9,8]
print(" Matrix A:\n",A)
print(" Matrix B:\n",B)

AB = np.cross(A,B)
print("\n Cross-product matrix of matrices, A and B:" "\n",AB)

 Matrix A:
 [2, 7, 4]
 Matrix B:
 [3, 9, 8]

 Cross-product matrix of matrices, A and B:
 [20 -4 -3]


On this final question, I simply again used a numpy command called np.cross to get the cross-product of the two Matrices, A and B.

#Lance G. Del Rosario
#CPE-202