<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Pyhton_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its operation

In [10]:
#The Matrices

import numpy as np

A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])

print(A)
print(B)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [11]:
#sum = A +B

print(A + B)

[[ 1 -3]
 [ 6  4]]


In [12]:
#difference1 = A - B

print(A-B)

[[-11   3]
 [  2  -2]]


In [13]:
#difference2 = B - B

print(B-B)

[[0 0]
 [0 0]]
