<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Python%20Exercise%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

##instantiate the given
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
Ai = np.linalg.inv(A)
B = np.array([[5],[6],[8]])

print("A\n",A)
print("\nInverse of A\n",Ai)
print("\nB\n",B)

##now solve
X = np.dot(Ai,B)
print("\nAnswer\n",X)


A
 [[1 1 1]
 [1 2 2]
 [1 2 3]]

Inverse of A
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]

B
 [[5]
 [6]
 [8]]

Answer
 [[ 4.]
 [-1.]
 [ 2.]]
