<a href="https://colab.research.google.com/github/LanceDelRosario/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its operation

In [1]:
#Example 1

import numpy as np 
#Create a 1x3 array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
#Example 2
#Creating a 2x2 matrix

b = np.array ([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [11]:
#Example 3
#Create a 3x3 matrix

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#Example 4
#Creating a constant array with all values are the same
#The format will be x = np.full((dimension,dimension),number)

d= np.full((5,5),6)
print (d)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [19]:
#Example 5
#Create a diagonal matrix
#The command "np.diagonal" will take the elements in the diagonal of the array

e = e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print (e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [33]:
#Example 6
#Creating an identity matrix
#We can use "np.eye" or "np.identity" it produces the same result
#Identity matrix is a matrix that has the same number in the diagonal

f = np.identity(3)
print (f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
#Example 7
#Creating a zero matrix
#Format will be "x = np.zeros((dimension,dimension))"

g = np.zeros((2,5))
print (g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
#Example 8
#Creating an empty matrix

h = np.empty((0,5))
print(h)

[]


In [36]:
#Example 9
#Addition of matrices

i = np.array([[1,2,3],[4,5,6]])
j = np.array([[1,2,3],[4,5,6]])
print(i+j)


[[ 2  4  6]
 [ 8 10 12]]


In [40]:
#Example 10
#Substraction of Matrices

k = np.array([[1,2,3],[4,5,6]])
l = np.array([[-1,2,4],[7,4,2]])

print(k)
print(l)
print(k-l)


[[1 2 3]
 [4 5 6]]
[[-1  2  4]
 [ 7  4  2]]
[[ 2  0 -1]
 [-3  1  4]]
